name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_ubuntu_autoconf:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autoreconf
      run: autoreconf -if
    - name: configure
      run: ./configure --enable-as-02
    - name: make
      run: make

  build_ubuntu_cmake:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: apt-get update && apt-get install -y
        cmake
        libxerces-c-dev
    - name: cmake
      working-directory: build
      run: cmake ..
    - name: make
      working-directory: build
      run: make
